In [1]:
import torch
import numpy as np
import pandas as pd 

In [69]:
label_dict = torch.arange(1, 5.5, 0.5) # torch도 arange가 있구나, need to detach from gpu
y_pred = torch.Tensor([[3.1533, 2.9453, 1.43434, 4.2311, 3.6454, 4.3331],
                       [3.1533, 2.9453, 1.43434, 4.2311, 3.6454, 4.3331],
                       [3.1533, 2.9453, 1.43434, 4.2311, 3.6454, 4.3331],
                       [3.1533, 2.9453, 1.43434, 4.2311, 3.6454, 4.3331],]) 
y_preds, label_dict, y_pred

(tensor([[3.1533, 2.9453, 1.4343, 4.2311, 3.6454, 4.3331],
         [3.1533, 2.9453, 1.4343, 4.2311, 3.6454, 4.3331],
         [3.1533, 2.9453, 1.4343, 4.2311, 3.6454, 4.3331],
         [3.1533, 2.9453, 1.4343, 4.2311, 3.6454, 4.3331]]),
 tensor([1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000, 4.5000, 5.0000]),
 tensor([[3.1533, 2.9453, 1.4343, 4.2311, 3.6454, 4.3331],
         [3.1533, 2.9453, 1.4343, 4.2311, 3.6454, 4.3331],
         [3.1533, 2.9453, 1.4343, 4.2311, 3.6454, 4.3331],
         [3.1533, 2.9453, 1.4343, 4.2311, 3.6454, 4.3331]]))

In [70]:
y_pred.shape

torch.Size([4, 6])

In [71]:
for y_preds in y_pred:
    for i in range(len(y_preds)):
        y_preds[i] = label_dict[(torch.abs(label_dict - y_preds[i]) == min(torch.abs(label_dict - y_preds[i]))).nonzero(as_tuple=False)]


In [72]:
y_pred.shape # [batch_size, ids, targe_cols]
y_pred

tensor([[3.0000, 3.0000, 1.5000, 4.0000, 3.5000, 4.5000],
        [3.0000, 3.0000, 1.5000, 4.0000, 3.5000, 4.5000],
        [3.0000, 3.0000, 1.5000, 4.0000, 3.5000, 4.5000],
        [3.0000, 3.0000, 1.5000, 4.0000, 3.5000, 4.5000]])