In [1]:
import torch
import numpy as np
import pandas as pd 

In [14]:
label_dict = torch.arange(1, 5.5, 0.5) # torch도 arange가 있구나, need to detach from gpu
y_pred = torch.Tensor([[0, 2.9453, 1.43434, 4.2311, 3.6454, 4.3331],
                       [3.1533, 2.9453, 1.43434, 4.2311, 3.6454, 4.3331],
                       [3.1533, 2.9453, 1.43434, 4.2311, 3.6454, 4.3331],
                       [3.1533, 2.9453, 1.43434, 4.2311, 3.6454, 4.3331],]) 
label_dict, y_pred

(tensor([1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000, 4.5000, 5.0000]),
 tensor([[0.0000, 2.9453, 1.4343, 4.2311, 3.6454, 4.3331],
         [3.1533, 2.9453, 1.4343, 4.2311, 3.6454, 4.3331],
         [3.1533, 2.9453, 1.4343, 4.2311, 3.6454, 4.3331],
         [3.1533, 2.9453, 1.4343, 4.2311, 3.6454, 4.3331]]))

In [15]:
y_pred.shape

torch.Size([4, 6])

In [16]:
for y_preds in y_pred:
    for i in range(len(y_preds)):
        y_preds[i] = label_dict[(torch.abs(label_dict - y_preds[i]) == min(torch.abs(label_dict - y_preds[i]))).nonzero(as_tuple=False)]


In [17]:
y_pred.shape # [batch_size, ids, targe_cols]
y_pred

tensor([[1.0000, 3.0000, 1.5000, 4.0000, 3.5000, 4.5000],
        [3.0000, 3.0000, 1.5000, 4.0000, 3.5000, 4.5000],
        [3.0000, 3.0000, 1.5000, 4.0000, 3.5000, 4.5000],
        [3.0000, 3.0000, 1.5000, 4.0000, 3.5000, 4.5000]])

In [18]:
torch.zeros_like(torch.empty(1))

tensor([0.])

In [12]:
torch.empty(0).squeeze()

tensor([])

In [13]:
torch.empty(0)

tensor([])

In [5]:
!pwd

/Users/qcqced/Desktop/GitHub/FeedBackPrize_3


In [10]:
test = pd.read_csv('./dataset_class/data_folder/MPL/train_df.csv')
test 

text_id                                          full_text  fold
0      423A1CA112E2  Modern humans today are always on their phone....     1
1      A8445CABFECE  Drivers should not be able to use phones while...     1
2      6B4F7A0165B9  The ability to stay connected to people we kno...     4
3      E05C7F5C1156  People are debating whether if drivers should ...     2
4      50B3435E475B  Over half of drivers in today's society have t...     0
...             ...                                                ...   ...
52350  9f63b687e76a  For many people they don't like only asking on...     3
52351  9d5bd7d86212  also people have different views and opinions ...     2
52352  f1b78becd573  Advice is something that can impact a persons ...     4
52353  cc184624ca8e  someone can use everything that many people sa...     2
52354  c8a973681feb  In conclusion asking for an opinion can be ben...     2

[52355 rows x 3 columns]

In [11]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52355 entries, 0 to 52354
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   text_id    52355 non-null  object
 1   full_text  52355 non-null  object
 2   fold       52355 non-null  int64 
dtypes: int64(1), object(2)
memory usage: 1.2+ MB


In [27]:
test1 = torch.tensor([0.21, 0.16, 0.10, 0.16, 0.21, 0.16], dtype=torch.float16)
test2 = torch.tensor([0.21, 0.16, 0.10, 0.16, 0.21, 0.16], dtype=torch.float32)
test1, test2

(tensor([0.2100, 0.1600, 0.1000, 0.1600, 0.2100, 0.1600], dtype=torch.float16),
 tensor([0.2100, 0.1600, 0.1000, 0.1600, 0.2100, 0.1600]))

In [28]:
torch.mul(test1, test2)

tensor([0.0441, 0.0256, 0.0100, 0.0256, 0.0441, 0.0256])

In [23]:
test1 * test2

tensor([0.0441, 0.0256, 0.0100, 0.0256, 0.0441, 0.0256])

In [ ]:

for i in range(6):
    score = score + (self.RMSE(yhat[:, i], y[:, i]) / self.num_scored)